- name: Hosting my web app in paticular path
  hosts: qa
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: creating a directory
      file:
        path: /opt/tomcat
        state: directory
    - name: install wget if it is a Debian OS
      apt:
        name: wget
        state: present
      when: ansible_distribution=="Debian"
    - name: Install jdk
      apt:
        name: default-jdk
        state: present
    - name: Delete the before extracted file
      file:
        path: /tmp/apache-tomcat.tar.gz
        state: absent    
    - name: Download Apache Tomcat
      get_url:
        url: https://downloads.apache.org/tomcat/tomcat-11/v11.0.8/bin/apache-tomcat-11.0.8.tar.gz
        dest: /tmp/apache-tomcat.tar.gz
    - name: Extract Tomcat
      unarchive:
        src: /tmp/apache-tomcat.tar.gz
        dest: /opt/tomcat
        remote_src: yes
    - name: Downloading webapp
      get_url:
        url: https://github.com/lerndevops/code/raw/refs/heads/main/sampleapp.war
        dest: /opt/tomcat/apache-tomcat-11.0.8/webapps
    - name: Start Tomcat
      shell: /opt/tomcat/apache-tomcat-11.0.8/bin/startup.sh



