- name: Using handler and notify
  hosts: qa
  become: yes
  vars_files:
    - vault.yml
  tasks:
    - name: Install apache
      apt:
        name: apache2
        state: present
    - name: copt file at /var/www/html
      copy:
        src: /etc/ansible/index.html
        dest: /var/www/html/index.html
        mode: '0644'
      notify: Restart apache2
  handlers:
    - name: Restart apache
      service:
        name: apache2
        state: restarted
